### ISSUE TITLE
Update third party lib to work out of the box with Arm64 (M1 mac)

### ISSUE THREAD

**Issue by Rodlik** [eclipse/mosaic#134]
* [x] **I have checked that this bug has not yet been reported by someone else.**

## Description

The current version of the sqllite lib does not run under arm64/M1. This issue has been resolved by sqlite-jdbc. Would it be possible to update the lib?
https://github.com/xerial/sqlite-jdbc/issues/562#issuecomment-741265278

## Steps to reproduce

Download current version of mosaic under arm64 and try to run out of the box. 

## Workaround

Remove lib/third-party/sqlite-jdbc-3.20.0.jar

Download the current version of sqlite-jdbc from https://github.com/xerial/sqlite-jdbc/releases/tag/3.36.0.1
Add lib/third-party/sqlite-jdbc-3.36.0.1.jar

## Affected modules

sqlite-jdbc-3.20.0.jar

## System information

* **Eclipse MOSAIC version:** 21.0
* **Operating System:** MacOS 11.4
* **JDK version/vendor:** openjdk 17 2021-09-14 / homebrew
* **SUMO version:** 1.9.2

**Comment by kschrab** [comment]
Thanks for reporting! I'll see what we can do here. Adding libraries and even upgrading versions requires IP checks by Eclipse Foundation which could take a while.

**Comment by kschrab** [comment]
Added CQ 23632 for approval by Eclipse IP Team

**Comment by birnbaum** [comment]
ah I'm sorry, I've overlooked that! thanks for your help, this works :)

**Comment by kschrab** [comment]
With the next release we ship an update jar of sqlite-jdbc which should solve this issue.
