### ISSUE TITLE
Matrix3d.multiply(Vector3d) does not match matrix element order

### ISSUE THREAD

**Issue by fhilg** [eclipse/mosaic#165]
# Description
- The method `Matrix3d.multiply(Vector3d)` does not match matrix element order
- `Matrix3d.get()` and `Matrix3d.set()` assume `Matrx3d.m` is in column-major order
- `Matrix3d.multiply(Vector3d)` assumes `Matrix3d.m` is in row-major order

## Code Sections
- https://github.com/eclipse/mosaic/blob/edcce483f8627c8a4e3b076aff25f5f3630acf93/lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java#L214
- https://github.com/eclipse/mosaic/blob/edcce483f8627c8a4e3b076aff25f5f3630acf93/lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java#L225

**Comment by kschrab** [comment]
@fabmax can you confirm?

**Comment by kschrab** [comment]
@fabmax apparently the old methods in Matrix3d expected row-major order, whereas we introduced get/set to work in column-major order. This explains why we have in Phabmacs this weird method in `BoxDynamics` where we switch rows and columns when transforming to jbullet Matrix3d:

```java
@Override
public void setOrientation(RotationMatrix ori) {
    body.getCenterOfMassTransform(tmpTransform);

    tmpTransform.basis.m00 = (float) ori.get(0,0);
    tmpTransform.basis.m01 = (float) ori.get(1,0);
    tmpTransform.basis.m02 = (float) ori.get(2,0);

    tmpTransform.basis.m10 = (float) ori.get(0,1);
    tmpTransform.basis.m11 = (float) ori.get(1,1);
    tmpTransform.basis.m12 = (float) ori.get(2,1);

    tmpTransform.basis.m20 = (float) ori.get(0,2);
    tmpTransform.basis.m21 = (float) ori.get(1,2);
    tmpTransform.basis.m22 = (float) ori.get(2,2);

    body.setCenterOfMassTransform(tmpTransform);
}
```

I would propose to fix `multiply` that it expects column-major order, and to fix the conversion in `BoxDynamics`.
