### ISSUE TITLE
Can the WGS84 coordinate system be preserved in the net file generated by OSM through scenario convert?

### ISSUE THREAD

**Issue by radiateboy** [eclipse/mosaic#217]
Can the WGS84 coordinate system be preserved in the net file generated by OSM through scenario convert?
eg Example Barnim: 
`<location netOffset="-395635.35,-5826456.24" convBoundary="0.00,0.00,15681.22,10052.78" origBoundary="395635.35,5826456.24,411316.57,5836509.02" projParameter="!"/>`

Use Netedit to open the net file,There is no geo-point.

**Comment by kschrab** [comment]
Hi, with the next release of scenario-convert we will add the proj4 definition to the netfile. In the mean time, you can simply replace the `"!"` with `"+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"` and correct [UTM zone number](https://www.dmap.co.uk/utmworld.htm).
