### ISSUE TITLE
Having problem while trying to install OMNeT++ 

### ISSUE THREAD

**Issue by JoaoGabrielTN** [eclipse/mosaic#380]
* [ ] **I have checked that this bug has not yet been reported by someone else.**

## Description
I tried to install OMNeT++ to use alongside with Eclipse MOSAIC through this guide: 
https://eclipse.dev/mosaic/docs/simulators/network_simulator_omnetpp/#installation-for-users

when I run this command:
./omnet_installer.sh \
    --installation-type USER \
    --omnetpp /path/to/omnetpp-5.5.1-src.tgz \
    --inet /path/to/inet-4.1.1-src.tgz \
    --federate /path/to/omnetpp-federate-23.1.zip

I get asked about some dependencies:

Are the following dependencies installed on the system?
 Libraries:
  libprotobuf-dev >= 3.7.0
  libxml2-dev
 Programs:
  unzip
  tar
  bison
  flex
  protoc
  gcc
  python
 y  Yes
 X  No, abort installation

And I have both python2 and python3 but it says: 
ERROR 'python' required, but it's not installed. Please install the package (sudo apt-get install for Ubuntu/Debian) and try again.

I can't understand why it still asks me about it.
(in the tutorial above the actual command executes ./omnet_install.sh, but the real  file is ./omnet_installer.sh. It would be nice if someone corrected this too).

## Steps to reproduce
The following lines are executed on my terminal (zsh):
cd <mosaic>/bin/fed/omnetpp
chmod +x omnet_installer.sh
./omnet_installer.sh \
    --installation-type USER \
    --omnetpp /path/to/omnetpp-5.5.1-src.tgz \
    --inet /path/to/inet-4.1.1-src.tgz \
    --federate /path/to/omnetpp-federate-23.1.zip
y

## Workaround
I did try to install python via terminal with apt, didn't work

## Affected modules

...

## System information

* **Eclipse MOSAIC version:** Latest
* **Operating System:** Linux Mint 21.2 Cinnamon
* **JDK version/vendor:** openjdk version "11.0.22" 2024-01-16
* **SUMO version:** Eclipse SUMO sumo Version 1.12.0

**Comment by JoaoGabrielTN** [comment]
Did solve it by running:
sudo apt install python-is-python3

but when executing ./omenet_installer.sh 
I got an compilation error:
src/util/ClientServerChannel.h:27:10: fatal error: ClientServerChannelMessages.pb.h: Arquivo ou diretório inexistente
   27 | #include "ClientServerChannelMessages.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by kschrab** [comment]
Hi,

> Did solve it by running:
> sudo apt install python-is-python3

yes, this would've been my suggestion, too. Unfortunately, the INET framework we are integrating currently relies on python2, thus expecting the command `python` to be available. When we have resources to look at an omnetpp/inet-upgrade, this issue might be obsolete, but until then the best solution is to install `python-is-python3`.
