### ISSUE TITLE
 The POM for org.eclipse.mosaic:mosaic-application:jar:24.1-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by Sumail2020** [eclipse/mosaic#394]
* [x] **I have checked that this bug has not yet been reported by someone else.**

## Description

...

## Steps to reproduce

...1. cd to "mosaic-main\app\tutorials\highway-management"
  2. run "mvn clean install"
  3. failed

## Workaround

...
![image](https://github.com/user-attachments/assets/83dfa422-c87b-4ab9-9679-255b24c7b79e)

## Affected modules

...

## System information

* **Eclipse MOSAIC version:*the newest MOSAIC source code from github* ...
* **Operating System:*windows 11* ...
* **JDK version/vendor:*17* ...
* **SUMO version:*1.20.0* ...

**Comment by Sumail2020** [comment]
Solved this by adding the following code to the pom.xml
<repositories>
    <repository>
        <id>repo.eclipse.org</id>
        <name>MOSAIC Repository</name>
        <url>https://repo.eclipse.org/content/repositories/mosaic</url>
    </repository>
</repositories>
![image](https://github.com/user-attachments/assets/ea5824cd-a48b-42e3-9e26-b18cd172c194)

**Comment by kschrab** [comment]
Always use the maven calls from the root directory of MOSAIC. If you want to build only one single application/module, you can use `mvn install -rf :highway-management`. This however works only if you've build the entire repo at least once.
